FROM eclipse-temurin:21-jdk-jammy

RUN apt-get update && apt-get install -y maven

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

EXPOSE 8083

CMD ["java", "-jar", "target/medical-protocol-1.0-SNAPSHOT.jar"]
